language: java

jdk:
  - openjdk8
  - openjdk12

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: releases
  api_key:
    secure: IZo09wa++Y/dsvavtftYBuUQrDy2crHc8zdj8oXx1b6ykKp/CsRr0QdF9vS8WxIECaUxgQ6W2lRAHM+tWeXpTcGdmZgCeuidiMq5SqViRrO9gyaQrw2MWC5IjsPIjAFu10B5e4brxjGsLtQUIQWDSZJNkp3pd+IKYSbMcKANKgW5j/GW4CDfgk3kvIFAJk/uk50G/GKiQXoNYwX/m9HcWMDvI/3RA7BEZy7l6Wv4pwlnMTgI76SJwMlsgsFWZGzsPtKyZFBj+aL1S0RQbPE8fah4sHd3XnH4qfpP34ZCFKnHcJ5GSdKiqN2Z5Ni5N8IjdVplcFL3mPVIEb0rwHs0FQU1xwd24Nq7qyPFw/DmlaDSPWg2iH2ExKEo6Y+gq1PjpEQlacS1+ppOoBjihLReZsUZClnemcxuI2qIm6U6rXUol2qmEykk+zKpDabG0QSoKbFYS3pv3lG15akxrCz6HtGcrm7vWE+6ccIAPsXeD8yHoViYRQNyUAYIfq7JQB/QzJTRWLn3xSpaiCDUl1bBP9YHSdxhO+BPeli1+2KE4POouaXQkjygJ2yDLmqkzI/G6z4FN4SaVrIJ0Peh1JdtT3Z7zePhywQxU61ils6RsEju1032Mmi9Q5jsB3NA76cGAYeEtRBtkM2P9l7gJEFH7RJDR6yq9Te5mWjlWwCozsM=
  file_glob: true
  file: "./build/libs/swordfish-*.jar"
  skip_cleanup: true
  on:
    tags: true

addons:
  sonarcloud:
    organization: agmcc
    token:
      secure: rjgEtplbUMOWe/TRKY6OaPAoXr6ZeW+KO3CDukvlXWAhBM+1sMQCTYYNarc8tMZ7DMtAMAYd4z9RCzq+ziZxmVdorpdyFlE0096ZakKnUQoYSUWPh0rk7pzlk+tb0GMfy0cKMF+nb0Gp+fXuex2MUiha4KewnyM4gUNs5RXvcRfCbqdcidqxJLZOtsxpK3ZUdzmH2VFopS0cib/5HCKfoQg29FxuX3kwTwt3nXcSF9UAMyiRk5Hw8L4vNhRj5dOqzFiebkUW9wwMd4D9dbn8KLhgy/76xE6f4urjatG/rOIKMpT6K96fDf3FfeBPcEJfnKD2cMj2GAYHpK2DbkI/YNKphen5P0jOZ+76ijdnkWYvqDDBaH0hPVn2iYPm9RkJREJwukQvBzgp2YiCitVaJJUSgQyvuoXkLaBxCY7BPPEb3dXxPnZa8AYOx3RztTL1goKYUBeYGqQ9m/CftjDYinne5K3byPa1fUX0exGyONw/59uzEL57hJuYmgIE86x7QI+tK2rRQBYZ+CaoFYMMySdaBBnY+7n4f5ntLBSfM8+fSjp0NL4uKSaqfU0OPGJOWyXPnO0vZHH+s5kjviju4n65EaYZQwz3p2qySPQoqhuoXuglf57lhBoIIGfhyOYQjD3GXlc9XBRQwrV4vQUcK/XsX35rdBQlIkwFp4LtVlk=

before_script:
  - "./gradlew jacocoTestReport"

script:
  - sonar-scanner
